
abstract class CustomStrings {
  static const chooseYourBike = "Choose Your Bike";
  static const off30Percent = "30% Off";
  static const all = "All";
  static const roadBike = "Road Bike";
  static const mountainBike = "Mountain Bike";
  static const peugotLR01 = "PEUGEOT - LR01 ";
  static const price1999 = r"$ 1,999.99";
  static const roadHelmet = "Road Helmet";
  static const smithTrade = "SMITH - Trade";
  static const price120 = r"$ 120";
  static const description = "Description";
  static const specification = "Specification";
  static const peugotDescription = "The LR01 uses the same design as the most iconic bikes from PEUGEOT Cycles' 130-year history and combines it with agile, dynamic performance that's perfectly suited to navigating today's cities. As well as a lugged steel frame and iconic PEUGEOT black-and-white chequer design, this city bike also features a 16-speed Shimano Claris drivetrain.";
  static const peugotSpecification = "The white Peugeot LR01 takes the design of the most emblematic bike of the 130 years of Peugeot Cycles adventure and combines it with an agile and dynamic experience perfectly suited to travel in a modern city. With its steel frame in the colors of the legendary black and white checkerboard, this city bike is also equipped with a vintage crankset, coupled to a Shimano Claris 2x8 speed transmission.";
  static const addToCart = "Add to Cart";
  static const myShoppingCart = "My Shopping Cart";
  static const pilotChromoly = "PILOT - CHROMOLY";
  static const price39999 = r"$ 3,999.99";
  static const apply = "Apply";
  static const checkout = "      Checkout";
  static const subtextTextField = "Your bag qualifies for free shipping";
  static const subtotal = "Subtotal:";
  static const deliveryFee = "ApplyDelivery Fee:";
  static const discount = "Discount:";
  static const total = "Total:";
  static const price6000 = r"$6,119.99";
  static const price0 = r"$0";
  static const discountPercent = "30%";
  static const shippingAddress = "shippingAddress:";
  static const deliveryDate = "Delivery Date:";
  static const shippingCosts = "Shipping Costs:";
  static const shippingType = "Shipping Type:";
  static const england = "England";
  static const date = "25.07.2023";
  static const costs = r"$ 120";
  static const typeOfShipping = "By Railways";
}